### ISSUE TITLE
General Release

### ISSUE THREAD

**Issue by frou** [cypheon/ocaml-docset#1]
Hi there - Thanks for making this. How about submitting it as a true User-Contributed-Docset so that it can be discovered and installed using the search in Dash's Preferences window?

**Comment by cypheon** [comment]
Hi, thanks for your interest in the docset!
I actually asked the author of Dash (initially to ask when the official Docset is going to be updated) if they would be willing to accept my Update as a user-contributed Docset. Bogdan (the author of Dash) didn't want to confuse user's by having two variants of one docset (which I totally understand), and said they'd eventually update the docset themself.
If you're interested, maybe contact the Dash support to show that there's some demand (I was told I was the first person to ask for an OCaml Docset update).
Until then, I'll try to keep this one resonably up-to-date so we can all enjoy the latest OCaml docs :)

**Comment by frou** [comment]
Oh right - that makes sense. Well good job anyway, it's so nice being able to browse docs via ergonomic search and with the sidebar.
